version: '3.8'

services:
  backend:
    build: ./back-end
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    volumes:
      - ./front-end:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    restart: unless-stopped
